# -*- coding:utf-8 -*-
import urllib
import urllib2
import re

class ClassesSpider:
  def __init__(self,root):
    self.rootUrl = root
    self.allClassUrl = self.rootUrl + 'allclasses-noframe.html'

  def run(self):
    try:
#find the doc version
        versionReg = re.compile('<!-- Generated by javadoc \((.*?)\)')
        request = urllib2.Request(self.allClassUrl)
        response = urllib2.urlopen(request)
        rspMsg = response.read()
        versionMatch = versionReg.findall(rspMsg)

    # I don't care if this is a doc or not, just get the first one, if nothing exist, panic will rasie    
        version = versionMatch[0]
        print version
#find the classes and interfaces, also find the href

        classReg = re.compile('<li><a href="(.*)".*?title="(.*?) in .*?"')
        allClass = classReg.findall(rspMsg)

        flag = True
        for cur in allClass:
          if flag:
            flag = False
            classReq = urllib2.Request(self.rootUrl + cur[0])
            classRes = urllib2.urlopen(classReq)
            classMsg = classRes.read()
            methodSummaryReg = re.compile('<td class="colLast"><code><span class="memberNameLink"><a href="(.*?#.*?)">(.*?)</a></span>')
            methodSummary = methodSummaryReg.findall(classMsg)
            for methods in methodSummary:
              print "link:%s, member:%s"%(methods[0], methods[1])
        
    except urllib2.URLError, e:
        if hasattr(e,"code"):
            print e.code
        if hasattr(e,"reason"):
            print e.reason

if __name__ == "__main__":
  rootUrl = 'http://api.mongodb.com/java/current/'
  spider = ClassesSpider(rootUrl)
  spider.run()

